# FinalParameters.py

blue_tag = '<span style="color:#115AEC">'
green_tag = '<span style="color:#44BB14">'
red_tag = '<span style="color:#F52F1C">'
b_span_tag = '</span>'
b_tag_open = '<b>'
b_tag_close = '</b>'

show_markers = '":{"showMarkers":true,'
no_markers = '":{"showMarkers":false,'
line_config = '"config":{"'
dashed_line = '"lineType":"dashed"'
solid_color = ',"color":"#FF9E00"}'
dashed_color = ',"color":"#FF0000"}'
solid_line = '"lineType":"solid"'
two_curl = '}}'
data_string = '{"data":'

bar_false = '":{ "type":"bar","rightAxis":false}'
bar_true = '":{ "type":"bar","rightAxis":true}'
dashed_line_true = '":{ "type":"line","rightAxis":true, "lineType":"dashed"}}'
solid_line_true = '":{ "type":"line","rightAxis":true, "lineType":"solid"}}'
dashed_line_false = '":{ "type":"line","rightAxis":false, "lineType":"dashed"}}'
solid_line_false = '":{ "type":"line","rightAxis":false, "lineType":"solid"}}'
config = '"config":{"chartConfig":{"'
data_string = '{"data":'
two_curl_comma = '}},'
three_curl = '}}}'
two_curl = '}}'

scatter_false = '":{ "type":"scatter","rightAxis":false'
dynamicTooltip_true = ', "dynamicTooltip": true}}'
color = ',"color":"green"'
xAxisTitle_start = ',"xAxisTitle":"'
xAxisTitle_end = '"'
yAxisTitle_start = ',"yAxisTitle":"'
yAxisTitleStart_right = ',"yAxisTitleRight":"'
yAxisTitle_end = '"'
chartTitle_start = ',"chartTitle":"'
chartTitle_end = '"'
chartSubTitle_start = ',"chartSubTitle":"'
chartSubTitle_end = '"'
chartFooterTitle_start = ',"chartFooterTitle":"'
chartFooterTitle_end = '"}'
scattered_true = ',"isScatteredPlot": true'
scattered_false = ',"isScatteredPlot": false'

waterfall_false = '":{ "type":"waterfall","rightAxis":false'
waterfall_true = '":{ "type":"waterfall","rightAxis":true'
raising_color = ',"risingColor":"#1A9901"'
falling_color = ', "fallingColor":"#AD0404"'
min_value = ', "minValue":'

def_color = '#FEE2B5'
highlight_color = '#FF9E00'
avg_color = '#FF0000'