name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: true

    - name: Verify Python and Pip version
      run: |
        python3 --version
        python3 -m pip --version

    - name: Install dependencies
      run: |
        python3 -m pip install --user --no-cache-dir -r requirements.txt
        python3 -m pip install --user --no-cache-dir gunicorn

    - name: Stop existing processes on port 8000
      run: |
        echo "Killing processes on port 8000..."
        sudo fuser -k 8000/tcp || true
        sleep 2
        sudo netstat -tulnp | grep 8000 || true

    - name: Restart Flask application
      run: |
        echo "Restarting flask_app service..."
        sudo systemctl restart flask_app
        sleep 5
        sudo systemctl status flask_app || true
        sudo netstat -tulnp | grep 8000 || true
        tail -n 50 /home/ec2-user/gunicorn.log || true

    - name: Restart Nginx
      run: sudo systemctl reload nginx

    - name: Print Deployment Success
      run: echo "Deployment successful!"